<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Created at' => 'Дата/время создания',
  'Created by' => 'Создатель',
  'Description' => 'Описание',
  'Editable' => 'Редактируемое',
  'Field Type could not be changed!' => 'Тип поля не может быть изменён!',
  'Fieldtype' => 'Тип поля',
  'ID' => 'Код',
  'Internal Name' => 'Внутреннее название',
  'Internal name already in use!' => 'Внутреннее название уже используется!',
  'Internal name could not be changed!' => 'Внутреннее название не удалось изменить!',
  'Invalid field type!' => 'Некорректный тип поля!',
  'LDAP Attribute' => 'Аттрибут LDAP',
  'Module' => 'Модуль',
  'Only alphanumeric characters allowed!' => 'Разрешены только буквы и цифры!',
  'Profile Field Category' => 'Категория поля профиля',
  'Required' => 'Обязательное',
  'Show at registration' => 'Показывать при регистрации',
  'Sort order' => 'Порядок сортировки',
  'Title' => 'Название',
  'Translation Category ID' => 'Код категории перевода',
  'Type Config' => 'Конфигурация типа',
  'Updated at' => 'Дата/время обновления',
  'Updated by' => 'Обновлено',
  'Visible' => 'Отображается',
);
